/* ============================================================================
 * 12-0 — Game config (static, hand-authored)
 * Pure data, no logic. Loaded as a classic script (globals below).
 *
 *   STEPS         — the 3 "how it works" cards on the home screen
 *   SETUPS        — the 4 team shapes (formations); each locks 5 role slots
 *   SWISS_STAGES  — the three Swiss stages of a Major (base opponent strengths)
 *   PLAYOFFS      — the single-elimination playoff rounds
 *
 * The draftable squads (SQUADS) and opponent names (OPP_POOL) live in
 * src/squads.js, which is generated by scripts/build-data.js.
 *
 * Player object (in squads.js): { n: nickname, c: country, r: era HLTV-style
 *   rating, awp: is an AWPer, roles: [functional role tags] }
 *   Optional provenance fields from the pipeline: src (source tag/url),
 *   est (true when the rating is estimated), and a squad-level lowConfidence.
 *   The engine ignores these extra fields.
 * Squads are unique per (team, year). reroll keys on the exact team name.
 * Role tags: awp | igl | entry | support | lurker | rifle | star
 * ==========================================================================*/

const STEPS = [
  { num: '01', title: 'Pick a setup', body: 'Choose one of four team shapes — your five role slots.' },
  { num: '02', title: 'Draft 5 legends', body: 'Each draw reveals a real squad. Pick one player. Repeat.' },
  { num: '03', title: 'Run the Major', body: 'Simulate all 12 matches. Survive every round for 12–0.' },
];

const SETUPS = [
  { id: 'standard', name: 'Standard', sub: 'One AWP · balanced core', roles: [
    { label: 'AWPer', code: 'AWP', tag: 'awp' },
    { label: 'In-Game Leader', code: 'IGL', tag: 'igl' },
    { label: 'Entry Fragger', code: 'ENT', tag: 'entry' },
    { label: 'Support', code: 'SUP', tag: 'support' },
    { label: 'Lurker', code: 'LRK', tag: 'lurker' } ] },
  { id: 'double', name: 'Double AWP', sub: 'AWP + flex · map control', roles: [
    { label: 'AWPer', code: 'AWP', tag: 'awp' },
    { label: '2nd AWP / Flex', code: 'AW2', tags: ['awp', 'rifle'] },
    { label: 'In-Game Leader', code: 'IGL', tag: 'igl' },
    { label: 'Entry Fragger', code: 'ENT', tag: 'entry' },
    { label: 'Support', code: 'SUP', tag: 'support' } ] },
  { id: 'firepower', name: 'Firepower', sub: 'Max aim · pure fragging', roles: [
    { label: 'Rifler', code: 'RIF', tag: 'rifle' },
    { label: 'Entry Fragger', code: 'ENT', tag: 'entry' },
    { label: 'AWPer', code: 'AWP', tag: 'awp' },
    { label: 'Lurker', code: 'LRK', tag: 'lurker' },
    { label: 'Support / IGL', code: 'S/I', tags: ['support', 'igl'] } ] },
  { id: 'rifle', name: 'Rifle-heavy', sub: 'No primary AWP · aggression', roles: [
    { label: 'Entry Fragger', code: 'ENT', tag: 'entry' },
    { label: 'In-Game Leader', code: 'IGL', tag: 'igl' },
    { label: 'Rifler', code: 'RIF', tag: 'rifle' },
    { label: 'Rifler', code: 'RIF', tag: 'rifle' },
    { label: 'Flex-AWP', code: 'FLX', tag: 'awp' } ] },
];

// A Major is three Swiss stages followed by single-elimination playoffs.
// `opp` is the base opponent strength for matches in that round (it rises round
// to round, so the run gets harder). Per-match variance is added in the engine.
//
// Swiss stage: play until 3 wins (advance, 3-x) or 3 losses (eliminated, x-3).
// A loss does NOT end your run in the Swiss — only 3 losses do.
const SWISS_STAGES = [
  { ph: 'SWISS STAGE 1', opp: 4.4 },
  { ph: 'SWISS STAGE 2', opp: 5.1 },
  { ph: 'SWISS STAGE 3', opp: 5.8 },
];

// Playoffs: best-of-three, single elimination. Lose once and you're out.
const PLAYOFFS = [
  { ph: 'QUARTERFINAL', opp: 6.2 },
  { ph: 'SEMIFINAL', opp: 6.4 },
  { ph: 'GRAND FINAL', opp: 6.6 },
];
